import yaml

crop_word_pool = {
    "Paddy": [
        "paddy", "dhan", "rice", "nellu", "ari", "puddling", "transplanting", 
        "system of rice intensification", "sri method", "direct seeded rice", "dsr", 
        "nursery bed", "mat nursery", "wetbed", "panicle", "tillering", "tillers", 
        "husk", "chaff", "hull", "hulling", "milling", "parboiling", "lodging", 
        "submergence", "standing water", "paddy field", "sawah", "blast disease", 
        "brown plant hopper", "bph", "sheath blight", "stem borer"
    ],
    "Wheat": [
        "wheat", "jau", "kanak", "tillering", "earhead", "spikelet", "awn", 
        "bearded wheat", "shattering", "crown root initiation", "cri stage", 
        "jointing stage", "milking stage", "dough stage", "threshing", 
        "combine harvester", "straw bale", "flour milling", "gluten", "rust disease", 
        "loose smut", "karnal bunt"
    ],
    "Cotton": [
        "cotton", "kapas", "kapasi", "square formation", "boll", "cotton boll", 
        "boll bursting", "ginning", "lint", "fuzz", "picking", "hand picking", 
        "defoliation", "topping", "bt cotton", "staple length", "bollworm", 
        "pink bollworm", "sucking pests"
    ],
    "Sugarcane": [
        "sugarcane", "sugar cane", "noble cane", "cane", "ganna", "ratoon", 
        "ratooning", "sett", "three budded setts", "earthing up", "detrashing", 
        "propping", "tying", "arrowing", "bagasse", "molasses", "jaggery making", 
        "gur", "brix value", "red rot", "whip smut", "cane borer"
    ],
    "Sugar Beet": [
        "sugar beet", "sugarbeet", "beet", "root development", "sucrose content", 
        "beet pulp", "bolting", "crown rot"
    ],
    "Bengal Gram": [
        "bengal gram", "gram", "chick pea", "chickpea", "kabuli", "chana", "kadala", 
        "nipping", "topping", "nodulation", "nitrogen fixation", "pod formation", 
        "podding", "deshi type", "kabuli type", "wilt disease", "pod borer"
    ],
    "Black Gram": [
        "black gram", "urd bean", "urd", "urad", "uzhunnu", "nodulation", 
        "podding", "yellow mosaic virus", "ymv", "shattering"
    ],
    "Green Gram": [
        "green gram", "moong bean", "moong", "mung", "cherupayar", "pod picking", 
        "nodulation", "yellow mosaic virus", "ymv", "powdery mildew"
    ],
    "Pigeon Pea": [
        "pigeon pea", "pigeonpea", "red gram", "arhar", "tur", "tuvar", "toor", 
        "perennial growth", "pod borer", "wilt resistant", "wooden stem"
    ],
    "Lentil": [
        "lentil", "masur", "masoor", "podding", "nodules", "rust resistant", 
        "cold tolerant"
    ],
    "Moth Bean": [
        "moth bean", "kidney bean", "dew gram", "dewgram", "matki", "drought resistant", 
        "arid farming", "mat bean"
    ],
    "Horse Gram": ["horse gram", "kulthi", "kultha", "muthira", "poor mans crop", "fallow land", "dryland farming"],
    "Cowpea": ["cowpea", "cow pea", "vegetable cowpea", "lobia", "chawli", "payar", "pod picking", "bush type", "trailing vine"],
    "Kidney Bean": ["kidney bean", "rajma", "rajmash", "french bean", "hill cultivation", "pod development"],
    "Ricebean": ["ricebean", "rice bean", "fodder pulse", "viny growth"],
    "Cluster Bean": ["cluster bean", "guar", "gavar", "guar gum", "mucilage", "drought hardy", "galli"],
    "French Bean": ["french bean", "bean", "staking", "bush bean", "pole bean", "protray nursery"],
    "Broad Bean": ["broad bean", "fava", "bakla", "cool season bean", "large pods"],
    "Faba Bean": ["faba bean", "horse bean", "windsor bean", "vicia faba", "cover crop"],
    "Lablab Bean": ["lablab bean", "lab lab", "mochai", "avara", "pandal system", "perennial vine", "pod picking"],
    "Indian Bean": ["indian bean", "vegetable bean", "sem", "hyacinth bean"],
    "Dolichos Bean": ["dolichos bean", "dolichos", "field bean", "wall bean"],
    "Winged Bean": ["winged bean", "chathurapayar", "four angled pods", "tuberous root"],
    "Runner Bean": ["runner bean", "scarlet runner", "perennial bean", "trellis"],
    "Yard Long Bean": ["yard long bean", "achinga", "pandal trailing", "long pods", "valli payar"],
    "Lathyrus": ["lathyrus", "khesari", "chickling vetch", "grass pea", "lethyrus", "lathyrism", "neurotoxin", "odap", "para crop"],
    "Maize": [
        "maize", "makka", "corn", "fodder maize", "baby corn", "chillum", "tasseling", 
        "tassel", "silking", "silk", "cob", "maize cob", "shucking", "detasseling", 
        "baby corn harvesting", "stover", "corn starch", "fall armyworm", "faw"
    ],
    "Pearl Millet": ["pearl millet", "bajra", "bulrush millet", "spiked millet", "kambu", "tillering", "earhead", "grain mold", "drought hardy", "downy mildew", "ergot"],
    "Sorghum": ["sorghum", "jowar", "great millet", "cholam", "ratoon", "earhead", "multi cut", "chari cutting", "hydrocyanic acid", "hcn content", "dhurrin", "shoot fly"],
    "Fodder Sorghum": ["fodder sorghum", "chari", "multi-cut fodder", "sorghum silage"],
    "Finger Millet": ["finger millet", "ragi", "mandika", "kooravu", "nursery transplanting", "earhead", "finger shaped spike", "tillering", "blast resistant"],
    "Barnyard Millet": ["barnyard millet", "kundiraivlli", "sawan", "sanwa", "fast maturing", "mid hills"],
    "Foxtail Millet": ["foxtail millet", "italian millet", "thenai", "navane", "kang", "bristle spike", "drought hardy"],
    "Kodo Millet": ["kodo millet", "kodara", "varagu", "waterlogging tolerant", "coarse grain"],
    "Proso Millet": ["proso millet", "common millet", "panivaragu", "chena", "hogm", "short duration", "catch crop"],
    "Little Millet": ["little millet", "samai", "kutki", "kodo-kutki", "tribal farming", "marginal lands"],
    "Barley": ["barley", "jau", "malting", "malt house", "hulless barley", "feed barley", "smut"],
    "Oats": ["oats", "oat", "fodder cutting", "oatmeal", "oat straw"],
    "Triticale": ["trriticale", "wheat rye hybrid", "cereal forage"],
    "Buckwheat": ["buckwheat", "buck wheat", "kaspat", "kuttu", "pseudo cereal", "frost sensitive", "honey bee foraging"],
    "Mustard": [
        "mustard", "rapeseed", "sarson", "raya", "toria", "african sarson", 
        "brown sarson", "gobhi sarson", "kaduku", "siliqua", "pod formation", 
        "oil extraction", "mustard cake", "thinning", "aphid attack", "alternaria blight"
    ],
    "Groundnut": [
        "groundnut", "ground nut", "pea nut", "peanut", "mung phalli", "mungphali", 
        "moongphali", "pegging", "peg formation", "pod development", "earthing up", 
        "decortication", "shelling", "oil cake", "haulms", "tikka leaf spot", "aflatoxin"
    ],
    "Soybean": ["soybean", "soy bean", "bhat", "soya", "nodulation", "soy milk", "oil processing", "pod clearwing", "girdle beetle"],
    "Sesame": ["sesame", "gingelly", "til", "sesamum", "ellu", "capsule shattering", "oil expeller", "phyllody disease"],
    "Castor": ["castor", "rehri", "rendi", "arandi", "avanakku", "spikes", "capsule", "capsule shedding", "nipping of central spike", "castor cake", "semi looper"],
    "Sunflower": ["sunflower", "suryamukhi", "surajmukhi", "capitulum", "head rot", "ray florets", "disc florets", "hand pollination", "honeybee pollination"],
    "Linseed": ["linseed", "alsi", "flax fiber", "linseed oil", "flaxseed", "rust disease"],
    "Safflower": ["safflower", "kusum", "kardi", "spiny leaves", "spineless variety", "carthamin dye", "oil mill"],
    "Niger": ["niger", "ramtil", "oil seed crop", "bee attractant", "shattering"],
    "Oil Palm": ["oil palm", "oilpalm", "fresh fruit bunches", "ffb", "frond", "frond pruning", "pollinating weevil", "palm oil mill", "kernel oil"],
    "Bottle Gourd": ["bottle gourd", "lauki", "dudhi", "churakka", "bower system", "trellis system", "pandal system", "3g pruning", "hand pollination", "trailing"],
    "Bitter Gourd": ["bitter gourd", "karela", "kaippakka", "pavakka", "bower system", "trellis system", "pandal system", "3g pruning", "hand pollination", "fruit fly trap"],
    "Pointed Gourd": ["pointed gourd", "parwal", "patol", "dioecious vine", "stem cuttings", "thatch propping"],
    "Ridge Gourd": ["ridge gourd", "turai", "peechinga", "pandal trailing", "angled gourd", "sponge net"],
    "Snake Gourd": ["snake gourd", "chichinda", "padavalanga", "hanging stone weight", "pandal structure", "elongated fruit"],
    "Sponge Gourd": ["sponge gourd", "smooth gourd", "ghiloda", "loofah scrubbing", "trellis system"],
    "Ivy Gourd": ["ivy gourd", "kundru", "tindora", "kovakka", "perennial runner", "root cuttings", "bower frame"],
    "Ash Gourd": ["ash gourd", "petha", "kumbalanga", "waxy coating", "petha making", "ground trailing"],
    "Ribbed Gourd": ["ribbed gourd", "kali tori", "luffa acutangula", "trellis"],
    "Spine Gourd": ["spine gourd", "kakrol", "kantola", "tuberous roots", "dioecious vine"],
    "Cucumber": ["cucumber", "kheera", "vellarikka", "polyhouse slicing", "parthenocarpic", "staking", "downy mildew"],
    "Muskmelon": ["muskmelon", "musk melon", "kharbooja", "riverbed farming", "netting on rind", "sugar brix"],
    "Watermelon": ["watermelon", "water melon", "tarbooz", "thannimathan", "riverbed sand farming", "mulching film", "thumping test"],
    "Snap Melon": ["snap melon", "poot", "cracking rind", "local dessert melon"],
    "Round Melon": ["round melon", "tinda", "indian squash", "flat round gourds"],
    "Long Melon": ["long melon", "kakri", "light green ribbed", "summer cooling vegetable"],
    "Pumpkin": ["pumpkin", "kaddu", "mathanga", "viny crawl", "long shelf life", "fruit fly infestation"],
    "Chapan Kaddu": ["chapan kaddu", "squash", "summer squash", "bush type gourd"],
    "Summer Squash": ["summer squash", "vegetable marrow", "zucchini type", "bush plant"],
    "Bush Squash": ["bush squash", "non-trailing gourd"],
    "Melon": ["melon", "gourd patch", "rind development"],
    "Okra": ["okra", "bhindi", "ladysfinger", "lady finger", "vendakka", "picking interval", "yellow vein mosaic virus", "ymvm", "fruit borer", "mucilaginous juice"],
    "Tomato": [
        "tomato", "tamatar", "thakkali", "staking", "trellising", "pruning suckers", 
        "indeterminate growth", "determinate growth", "protray nursery", 
        "blossom end rot", "bacterial wilt", "early blight", "damping off"
    ],
    "Potato": [
        "potato", "aloo", "urulakkizhangu", "earthing up", "tuberization", 
        "seed tuber", "true potato seed", "tps", "dehaulming", "sprouting", 
        "cold storage", "late blight", "early blight", "potato tuber moth"
    ],
    "Onion": ["onion", "pyaz", "savala", "ulli", "protray nursery", "bulb development", "bolting", "detopping", "curing", "storage rot", "thrips damage"],
    "Brinjal": ["brinjal", "eggplant", "baingan", "vazhuthananga", "protray nursery", "ratooning", "staking", "shoot and fruit borer", "little leaf disease"],
    "Cauliflower": ["cauliflower", "gobi", "blanching", "curd stage", "buttoning", "riciness", "whiptail disease", "diamondback moth"],
    "Cabbage": ["cabbage", "patta gobi", "muttagobi", "head formation", "wrapper leaves", "splitting head", "diamondback moth", "black rot"],
    "Chinese Cabbage": ["chinese cabbage", "pekinensis", "loose headed lettuce type"],
    "Broccoli": ["broccoli", "sprouting head", "central curd", "axial shoots"],
    "Brussels Sprouts": ["brussels sprouts", "brussils sprouts", "axillary buds", "miniature cabbages", "stalk stripping"],
    "Capsicum": ["capsicum", "bell pepper", "shimla mirch", "polyhouse cultivation", "greenhouse", "pruning to two stems", "staking", "fertigation", "thrips and mites"],
    "Chillies": ["chillies", "chilli", "chili", "pepper", "mirch", "mulaku", "drying yard", "chilli leaf curl", "anthracnose", "dieback", "capsaicin extraction"],
    "Carrot": ["carrot", "gajar", "root splitting", "forking", "cavity spot", "steckling production"],
    "Radish": ["radish", "mooli", "mullangi", "pithiness", "root bolting", "flea beetle"],
    "Turnip": ["turnip", "saljam", "shalgam", "root swelling", "cool climate crop"],
    "Pea": ["pea", "peas", "field peas", "garden peas", "matar", "pattani", "staking", "pod shelling", "powdery mildew", "wilt resistant"],
    "Garden Pea": ["garden pea", "green peas picking", "tender pods"],
    "Butter Pea": ["butter pea", "sugar snap pea", "edible podded pea"],
    "Drumstick": ["drumstick", "drum stick", "moringa", "muringakka", "limb pruning", "pod collection", "annual moringa", "perennial drumstick", "hairy caterpillar"],
    "Spinach": ["spinach", "palak", "cheera", "staggered clipping", "leaf cutting", "bolting stage"],
    "Leafy Vegetable": ["leafy vegetable", "greens", "cutting interval", "shelf life wetting"],
    "Lettuce": ["lettuce", "heading stage", "hydroponic lettuce", "leaf rot"],
    "Knol-Khol": ["knol-khol", "knolkhol", "ganth gobi", "knob development", "woody stem transition"],
    "Amaranthus": ["amaranthus", "amaranth", "cheera", "leaf clipping", "grain amaranth", "damping off", "leaf webber"],
    "Beetroot": ["beetroot", "beet root", "garden beet", "stock beet", "root swelling", "zonation ring error"],
    "Colocasia": ["colocasia", "arvi", "arbi", "chembu", "corm development", "sprouting tubers", "leaf blight"],
    "Elephant Foot Yam": ["elephant foot yam", "amarphophallus", "surankand", "suran", "chena", "corm cutting", "mulching", "pit planting", "acridity removal"],
    "Arum": ["arum", "kachu", "taro corm", "wetland root crop"],
    "White Yam": ["white yam", "dioscorea rotundata", "tuber staking"],
    "Greater Yam": ["greater yam", "kachil", "vine staking", "mounding pits", "large tubers"],
    "Lesser Yam": ["lesser yam", "rafula", "cherukizhangu", "cluster tubers", "trailing support"],
    "Sweet Potato": ["sweet potato", "shakarkand", "madhurakizhangu", "vine cuttings", "tuberous root development", "weevil attack"],
    "Tapioca": ["tapioca", "cassava", "kappa", "maracheeni", "setts", "stem cuttings", "mounding", "tuber harvesting", "sago making", "starch extraction", "mosaic disease"],
    "Turmeric": ["turmeric", "haldi", "manjal", "rhizome", "mother rhizome", "finger rhizome", "ridge and furrow", "boiling", "curing", "polishing", "rhizome rot"],
    "Ginger": ["ginger", "adrak", "inji", "rhizome", "seed rhizome", "shading", "mulching", "soft rot", "rhizome rot"],
    "Garlic": ["garlic", "lahsun", "veluthulli", "cloves", "planting cloves", "curing", "braiding", "bulb formation"],
    "Coriander": ["colander", "dhaniya", "malli", "seed splitting", "leaf plucking", "bolting control"],
    "Cumin": ["cumin", "jeera", "jeerakam", "seed crop", "wilt sensitive", "blight disease"],
    "Fennel": ["fennel", "saunf", "perumjeerakam", "umbels crop", "seed collection"],
    "Fenugreek": ["fenugreek", "methi", "uluva", "leaf cutting", "seed pulse", "root nodules"],
    "Cardamom": ["cardamom", "elaichi", "elathari", "shade overhead", "capsule picking", "cardamom curing smoke", "capsule borer"],
    "Large Cardamom": ["large cardamom", "badi elaichi", "himalayan cultivation", "curing oven"],
    "Clove": ["clove", "laung", "karayampoo"],
    "Cinnamon": ["cinnamon", "dalchini", "karuvapatta", "bark peeling", "coppicing", "quill making"],
    "Curry Leaf": ["curry leaf", "kadi patta", "kariveppila", "pruning bush", "leaf stripping"],
    "Mint": ["mint", "mentha", "pudina", "runner cuttings", "essential oil distillation", "sucker division"],
    "Bishop's Weed": ["bishop's weed", "bishops weed", "ajwain", "ayamooham", "umbel flower"],
    "Dill Seed": ["dill seed", "suva", "chathakuppa", "seed foliage"],
    "Saffron": ["saffron", "kesar", "corm planting", "stigma plucking", "drying tray"],
    "Vanilla": ["vanilla", "hand pollination", "curing vine beans", "sweating box", "looping support vine"],
    "Bay Leaf": ["bay leaf", "tejpatta", "tree pruning", "leaf air drying"],
    "Celery": ["celery", "stalk blanching", "petiole harvest"],
    "Nutmeg": ["nutmeg", "jaiphal", "jathikka", "mace layer", "seed drying", "grafting dioecious"],
    "Mango": ["mango", "aam", "manga", "grafting", "epicotyl grafting", "stone grafting", "alternate bearing", "malformation", "hopper control", "fruit fly trap"],
    "Banana": [
        "banana", "kela", "vazha", "ethakka", "suckers", "sword sucker", 
        "water sucker", "tissue culture", "desuckering", "denaveling", 
        "mattocking", "propping", "bunch covering", "pseudostem", "ratooning", 
        "panama wilt", "sigatoka leaf spot", "bunchy top"
    ],
    "Citrus": ["citrus", "rootstock", "budding", "citrus canker", "dieback", "gummosis"],
    "Acid Lime": ["acid lime", "cherunaranga", "air layering", "pruning spines", "citrus canker"],
    "Lemon": ["lemon", "nimbu", "naranga", "kagzi lime", "dieback"],
    "Mosambi": ["mosambi", "sweet lime", "t-budding", "rootstock selection"],
    "Orange": ["orange", "santra", "mandarin orchard", "declining yield"],
    "Guava": ["guava", "amrood", "perakka", "mealybug", "guava wilt", "bending method", "bahar regulation"],
    "Papaya": ["papaya", "papita", "omakka", "kappanga", "papain extraction", "gynodioecious", "ringspot virus", "damping off"],
    "Pomegranate": ["pomegranate", "anar", "mathalam", "bahar treatment", "air layering", "fruit borer butterfly", "bacterial blight"],
    "Apple": ["apple", "seb", "rootstock grafting", "chilling requirement", "scab disease", "spur formation", "thinning fruit"],
    "Grape": [
        "grape", "grap", "angoor", "munthiri", "bower system", "trellis system", 
        "pruning", "forward pruning", "back pruning", "girdling", "dipping", 
        "ga3 application", "downy mildew", "powdery mildew"
    ],
    "Litchi": ["litchi", "lychee", "air layering", "fruit cracking", "girdling branch"],
    "Sapota": ["sapota", "chiku", "chikoo", "inarching grafting", "rayan rootstock", "milky latex"],
    "Jackfruit": ["jackfruit", "jack fruit", "kathal", "chakka", "flake processing", "perennial timber fruit", "fruit rot borer"],
    "Aonla": ["aonla", "amla", "nellikka", "budding patch", "pruning branch", "internal necrosis"],
    "Ber": ["ber", "jujube", "ring budding", "heavy pruning", "fruit fly resistant"],
    "Jamun": ["jamun", "blackberry", "njava", "seed propagation", "deep root orchard"],
    "Coconut": [
        "coconut", "nariyal", "thenga", "crown", "frond", "spadix", 
        "button shedding", "copra", "copra drying", "oil milling", "coir extraction", 
        "toddy tapping", "rhinoceros beetle", "red palm weevil", "root wilt"
    ],
    "Arecanut": ["arecanut", "areca nut", "supari", "adakka", "chali", "supari making", "shading", "dehusking", "yellow leaf disease", "mahali disease"],
    "Cashew": ["cashew", "kaju", "kasuvandi", "softwood grafting", "cashew apple juice", "nut roasting", "tea mosquito bug"],
    "Walnut": ["walnut", "akhrot", "grafting hills", "shell cracking quality"],
    "Almond": ["almond", "badam", "graft compatibility", "hull color splitting", "kernel quality"],
    "Pecan Nut": ["pecan nut", "pecannut", "stratification seeds"],
    "Chestnut": ["chestnut", "acid soil orchard", "nut roasting"],
    "Custard Apple": ["custard apple", "sitaphal", "seethapazham", "defoliation pruning", "mealybug infestation"],
    "Pineapple": ["pineapple", "kaitha chakkay", "suckers planting", "slips", "crown planting", "flower induction", "ethrel spray"],
    "Strawberry": ["strawberry", "runner plants", "plastic mulching bed", "runner removal", "polyhouse berries"],
    "Peach": ["peach", "adu", "chilling hours", "thinning fruits"],
    "Pear": ["pear", "nashpati", "scion framework", "flesh grit removal"],
    "Plum": ["plum", "aloobukhara", "stone fruit management"],
    "Apricot": ["apricot", "khubani", "dry fruit processing"],
    "Fig": ["fig", "anjeer", "athi", "notching branch", "cuttings plant", "rust control"],
    "Kiwi Fruit": ["kiwi fruit", "kiwi", "t-bar trellis", "vine training system", "dioecious sorting"],
    "Avocado": ["avocado", "avacado", "butter fruit graft", "root rot avoidance"],
    "Loquat": ["loquat", "subtropical orchard", "cluster thinning"],
    "Passion Fruit": ["passion fruit", "trellis vine training", "hand pollination vine", "pulp scoop"],
    "Sweet Cherry": ["sweet cherry", "cherry", "bird netting protection"],
    "Persimmon": ["persimmon", "astringency removal", "fruit dropping management"],
    "Kokum": ["kokum", "rind solar drying", "softwood graft", "western ghats crop"],
    "Bael": ["bael", "bail", "sirphal", "hard rind fruit", "budding patch graft"],
    "Gunda": ["gunda", "lahsoda", "pickle fruit collection"],
    "Karonda": ["karonda", "koronda", "hedgerow barrier", "iron rich berries"],
    "Palmyra": ["palmyra", "karimpana", "neera tapping", "jaggery boiling palm"],
    "Lehberry": ["lehberry", "seabuckthorn", "cold desert orchard", "thorny harvest"],
    "Mulberry": ["mulberry", "shahtoot", "sericulture silkworm feeding", "pruning mulberry bushes"],
    "Olive": ["olive", "jaitun", "oil cold press extraction", "mechanical shaking harvest"],
    "Tobacco": ["tobacco", "khaini", "pogayila", "topping of flower", "desuckering leaves", "flue curing barns", "priming leaves", "bidi making"],
    "Jute": ["jute", "patson", "patua", "retting water", "stripping fiber", "ribbon retting"],
    "Sunnhemp": ["sunnhemp", "sunn hemp", "patua", "green manure ploughing", "retting process"],
    "Roselle": ["roselle", "mesta", "calyx harvesting", "fiber stripping"],
    "Mesta": ["mesta", "fiber crop retting", "stem peeling"],
    "Rubber": [
        "rubber", "tapping", "tapping panel", "latex", "latex collection", 
        "acid coagulation", "rubber sheets", "smoke house", "ethrel stimulant", 
        "panel dryness"
    ],
    "Tea": [
        "tea", "chai", "theela", "plucking", "two leaves and a bud", "pruning", 
        "tiipping", "withering", "rolling", "fermentation", "drying", "estate", 
        "blister blight"
    ],
    "Coffee": [
        "coffee", "kaapi", "shading", "silver oak", "blossom shower", "backing shower", 
        "picking", "berries", "parchment coffee", "cherry coffee", "pulping", 
        "coffee berry borer", "white stem borer"
    ],
    "Cocoa": ["cocoa", "pod breaking", "bean fermentation", "sweating", "drying", "chupon", "fan branches", "black pod rot"],
    "Opium Poppy": ["opium poppy", "opium", "afeem", "latex lancing", "capsule scratching", "poppy seed extraction"],
    "Hemp": ["hemp", "bhang", "canabis", "cannabis", "ganja", "cbd flower harvest", "retting stalks"],
    "Betel Vine": ["betel vine", "paan", "vettila", "bareja", "pandal", "propping", "lowering of vines", "foot rot disease"],
    "Jojoba": ["jojoba", "desert oil crop", "seed pressing"],
    "Jatropha": ["jatropha", "ratanjot", "kattavanakku", "biodiesel seeds", "oil transesterification"],
    "Tumba": ["tumba", "desert sand stabilizer", "seed oil harvest"],
    "Rose": ["rose", "gulab", "panineer", "pruning bushes", "dieback control", "rose water distillation", "grafting eye budding"],
    "Marigold": ["marigold", "genda", "chendumalli", "pinching terminal shoot", "flower picking", "nematode trap crop"],
    "Jasmine": ["jasmine", "chameli", "mulla", "flower bud collection", "layering plant propagation", "concrete extraction essence"],
    "Gladiolus": ["gladiolus", "corm planting", "spike cutting", "cormel storage", "floral spiking stage"],
    "Chrysanthemum": ["chrysanthemum", "guldaudi", "jomanthi", "root suckers separation", "pinching and disbudding", "photoperiod management"],
    "Tuberose": ["tuberose", "rajnigandha", "bulb splitting", "spike harvesting flower", "single double flowering classes"],
    "Hibiscus": ["hibiscus", "gurhal", "chembarathi", "cuttings potting", "mealybug control"],
    "Gerbera": ["gerbera", "polyhouse cut flower", "raised beds planting", "crown rot vulnerability"],
    "Carnation": ["carnation", "pinching terminal", "calyx splitting error", "netting wire support", "polyhouse crop"],
    "China Aster": ["china aster", "china astor", "seed bed raising", "rust flower spot"],
    "Anthurium": ["anthurium", "shade net house", "spathe development", "growing media charcoal husk"],
    "Lilies": ["lilies", "lilliums", "lily", "bulb chilling requirement", "polyhouse bulb crops"],
    "Cymbidium": ["cymbidium", "orchid potting bark", "mist spray house", "spike staking"],
    "Zantedeschia": ["zantedeschia", "ventedeschia", "calla lily bulb management"],
    "Crossandra": ["crossandra", "kanakambaram", "seed dynamic clipping", "triploid varieties", "wilt control"],
    "Periwinkle": ["periwinkle", "sadabahar", "shavamnaari", "alkaloid leaf extraction", "drought flower garden"],
    "Oleander": ["oleander", "kaner", "arali", "hardy shrub pruning"],
    "Coleus": ["coleus", "caleus", "ornamental foliage stem cuttings", "root medicinal harvest"],
    "Berseem": ["berseem", "barseem", "forage cuttings", "egyptian clover multicut", "fodder seeding"],
    "Lucerne": ["lucerne", "alfalfa", "rajka bajri", "deep root forage", "protein rich green feed", "multicut alfalfa"],
    "Napier Grass": ["napier grass", "napier", "bajra napier hybrid", "root slips planting", "stem cuttings tool", "chaff cutter", "multicut fodder grass"],
    "Buffel Grass": ["buffel grass", "anjan grass", "pasture seeding drylands", "pasture grazing"],
    "Sudan Grass": ["sudan grass", "sorghum sudan hybrid", "forage grazing cutting"],
    "Guinea Grass": ["guinea grass", "shade tolerant pasture", "root slips planting"],
    "Sen Grass": ["sen grass", "pasture range management"],
    "Setaria Grass": ["setaria grass", "tussock grass pasture", "hill grass forage"],
    "Tall Fescue Grass": ["tall fescue grass", "temperate region pasture", "turf grass variant"],
    "Ryegrass": ["ryegrass", "rye grass", "overseeding winter pasture", "forage lawn mix"],
    "Marvel Grass": ["marvel grass", "bund pasture management", "semi arid forage"],
    "Dinanath Grass": ["dinanath grass", "annual fodder grass seeding"],
    "Dharaf Grass": ["dharaf grass", "arid zone rangeland grass"],
    "Golden Timothy": ["golden timothy", "golden thimothy", "swampy region forage grass"],
    "Velimasal": ["velimasal", "hedge lucerne", "perennial pasture legume seeding"],
    "Dhaincha": ["dhaincha", "green manuring crop", "sesbania flooding survival", "nitrogen fixation biofertilizer"],
    "Indian Clover": ["indian clover", "senji", "sweet clover", "winter green manure legume"],
    "White Clover": ["white clover", "shaftal", "temperate pasture blend", "legume lawn fixing"],
    "Red Clover": ["red clover", "forage ley cropping", "rotational grazing legume"],
    "Persian Clover": ["persian clover", "shaftal clover multi cut"],
    "Teosinte": ["teosinte", "maize wild ancestor fodder crop"],
    "Stylosanthes": ["stylosanthes", "stylo", "leguminous pasture enrichment", "stylo mat style crop"],
    "Pillipesara": ["pillipesara", "rice fallow green manure", "dual purpose pulse fodder"],
    "Birdwood Grass": ["birdwood grass", "arid desert pasture grass"],
    "Teak": ["teak", "sagoan", "thekku", "stump planting", "thinning timber woods", "teak defoliator pest", "silviculture harvest"],
    "Poplar": ["poplar", "agroforestry rows", "block plantation timber", "short rotation wood", "matchstick industry wood"],
    "Eucalyptus": ["eucalyptus", "eculeptous", "nilgiri", "clonal plantation poles", "coppicing management", "pulpwood logging"],
    "Neem": ["neem", "aryaveppu", "azadirachtin spray", "neem cake biofertilizer", "neem kernel grinding"],
    "Babul": ["babul", "babool", "wasteland afforestation", "thorny agroforestry tree"],
    "Sandalwood": ["sandalwood", "sandal wood", "chandan", "chandanam", "host plant parasite relationship", "heartwood spike disease", "oil extraction wood distillation"],
    "Sal Wood": ["sal wood", "salwood", "natural regeneration forest", "railway sleeper timber"],
    "Chinar Tree": ["chinar tree", "valley plantation pruning", "ornamental avenue tree"],
    "Aloe Vera": ["aloe vera", "ghritkumari", "kattarvazha", "leaf pup peeling", "mucilage gel extraction", "sucker plant propagating"],
    "Tulsi": ["tulsi", "basil", "thulasi", "seed dynamic picking", "herbal leaf distillation", "dieback trimming"],
    "Safed Musli": ["safed musli", "musli", "fasciled root peeling", "drying roots", "chlorophytum planting beds"],
    "Shatavari": ["shatavari", "satawar", "shatavali", "tuberous root digging", "climbing vine propping", "peeling tubers"],
    "Stevia": ["stevia", "leaf clipping harvesting", "calorie free sweetener processing", "plug seedlings house"],
    "Mushroom": [
        "mushroom", "koon", "spawning", "spawn", "compost", "casing", 
        "cropping", "flushes", "mushroom beds", "spawn running", "button mushroom", 
        "oyster mushroom", "milky mushroom"
    ],
    "Beekeeping": ["beekeeping", "honeybee", "apiary setup", "honey extractor machine", "hive inspection frame", "queen bee rearing", "super chamber hive"],
    "Honey Plant": ["honey plant", "bee forage flora", "nectar crop planning"],
    "Karan Rai": ["karan rai", "brassica carinata", "oilseed crop brown"],
    "Guar": ["guar", "gwar", "guar gum seed splitting", "endosperm extraction"],
    "Kolanchi": ["kolanchi", "tephrosia purpurea", "wild green manure crop", "sandy soil restoration"],
    "Rocket Salad": ["rocket salad", "taramira", "oil processing drought crop", "erucic acid seeds"]
}

# Structure the data according to the target blueprint
yaml_data = {"Crops": {}}

for crop, words in crop_word_pool.items():
    # Convert name format to lower snake_case for the YAML keys
    yaml_crop_key = crop.lower().replace(" ", "_").replace("-", "_").replace("'", "")
    
    yaml_data["Crops"][yaml_crop_key] = {
        "keywords": words,
        "typos": [] # Empty list ready for future manual or programmatic typo entries
    }

# Export directly to a production-ready file with clean block indentations
with open("crops.yaml", "w", encoding="utf-8") as file:
    yaml.dump(yaml_data, file, sort_keys=False, default_flow_style=False, allow_unicode=True)

print("crops.yaml built with 100% data integrity.")